salience 100
when	
    $result : MediationResult(step == MediationResult.STEP_4_RESOLVE_ITEM)
    $field : PricingField( name == "duration", resultId == $result.id)
	
    // determine if numberDialled is international 
    PricingField( numberDialled : strValue, name == "numberDialled",
	resultId == $result.id)

    //Call function instead.  getInternational
    eval(getInternational(numberDialled))
	
then
	$result.getLines().add(newLine(112, new BigDecimal($field.getStrValue())));
	$result.setStep(MediationResult.STEP_5_PRICING);
	update( $result );
	PricingResult request = priceRequest(112, $result); // because it will be converted to this...
	insert( request );
	LOG.debug("is_international rule Price request " + request + " record " + $result.getRecordKey());
