salience 90
when	
    $result : MediationResult(step == MediationResult.STEP_4_RESOLVE_ITEM)
    $field : PricingField( name == "duration", resultId == $result.id)
	
    // determine if numberDialled is international 
    PricingField( numberDialled : strValue, name == "numberDialled",
	resultId == $result.id)

    //Call function getUKLL to see if number is UK landline
//    boolean isUKLL = false;
//    isUKLL = getUKLL(numberDialled);
//    eval(isUKLL)
    eval(getUKLL(numberDialled) == true)
	
then
	$result.getLines().add(newLine(107, new BigDecimal($field.getStrValue())));
	$result.setStep(MediationResult.STEP_5_PRICING);
	update( $result );
	PricingResult request = priceRequest(107, $result); // call pricing function
	insert( request );
	LOG.debug("isUKLL rule Price request " + request + " record " + $result.getRecordKey());

