package InternalEventsRulesTask520

#imports
import com.sapienter.jbilling.server.order.event.OrderToInvoiceEvent
import com.sapienter.jbilling.server.order.db.OrderDTO
import com.sapienter.jbilling.server.order.db.OrderLineDTO

rule 'Modify order'
when
        OrderToInvoiceEvent(userId == 1010)
        order : OrderDTO(notes == "Change me.")
then
        order.setNotes("Modified by rules.");

        // delete order lines with item id 1
        for (OrderLineDTO line : order.getLines()) {
            if (line.getItemId().equals(new Integer(1))) {
                line.setDeleted(1);
            }
        }
end
